cloudify-cosmo/cloudify-manager-install

README.md

In this PR, the link to the  `create_rpm.sh` script in the README is fixed.

Fix create_rpm.sh link in readme

---

packaging/create_rpm.sh
packaging/provision.sh

* Validate user has sudo permissions
* Quit early if the resources URL wasn't provided
* Validate if pip is installed
* Allow installing pip from the script (but don't make it mandatory, as pip may already be installed)

Several improvements to the create_rpm.sh script

---

cfy_manager/components/cli/cli.py

This allows the install process to remain idempotent, even if
different passwords were generated between installs

Split profiles use command into use + set

---

cfy_manager/main.py
cfy_manager/utils/certificates.py

This should be useful mostly for development/testing purposes,
because until now, it was impossible to have a proper external
cert when working with image-based managers (those are created
with 127.0.0.1 as the public IP).

Allow generating external certs from `cfy_manager`

---

cfy_manager/components/influxdb/influxdb.py
cfy_manager/components/logstash/logstash.py
cfy_manager/components/nginx/nginx.py
cfy_manager/components/postgresql/postgresql.py
cfy_manager/components/rabbitmq/rabbitmq.py
cfy_manager/main.py
packaging/create_rpm.sh

1. Don't delete the config.yaml file - mark is as an RPM config, which leaves a `config.yaml.rpmsave` file after `yum remove`.
2. Add a required `--force` flag.
3. Remove several users (like we did in the old teardown)

Several `cfy_manager remove` improvements

---

cfy_manager/components/manager/manager.py
packaging/create_rpm.sh

This is a first step to get the files to the correct place.
After this the single tar build process is intended to be rolled into here (thus skipping the single tar step entirely).

CFY-7512 Move files to intended locations

---

cfy_manager/utils/common.py

This is because the newest NodeJS package is archived in this format

Allow untaring tar.xz archives

---

cfy_manager/components/validations.py

Otherwise, the `nginx` installation will fail, and we want to error out as soon as possible.

Raise an error if OpenSSL version is smaller than 1.0.2

---

cfy_manager/components/stage/stage.py

And force its recreation anyway. Otherwise, a
bootstrap->teardown->bootstrap scenario will fail on the link creation

CFY-7624 Remove symlink from /usr/bin/node when tearing down

---

cfy_manager/config.py
cfy_manager/main.py
packaging/create_rpm
setup.py

The idea here is that some arguments may be passed via the command line (like the IPs) or generated during the configuration process (like the admin password), so it makes sense to preserve those in the config file, in order to be able to rerun the configuration/installation with the same values without having to provide them again (or, in the case of generation, without having to keep them elsewhere).

CFY-7684 Preserve configuration between runs of install/configure

---

cfy_manager/components/validations.py

The tuple might look like overkill for this, but it might prove useful
in the future if we validate more inputs (e.g. admin password)

CFY-7681 Print better validation errors when required inputs are missing

---

cfy_manager/components/nginx/config/nginx.conf

No real reason to display the nginx version, and it just makes it easier for automated vulnerability scanners to exploit our system.

CFY-7710 Hide nginx version in the Server header

---

cfy_manager/components/restservice/restservice.py

Reverts cloudify-cosmo/cloudify-manager-install#86
This isn't actually needed, because removing rest-service also removes premium,
because rest-service is a dependency of premium

Revert "When uninstalling, also remove cloudify-premium"

---

config.yaml

We are often asked about what `public_ip` is for and how should the manager be installed in environments with no floating IP's...

Comment update

---

cfy_manager/components/restservice/config/cloudify-rest.conf
cfy_manager/components/restservice/restservice.py

If the premium rpm was installed, we're using the premium edition,
otherwise community.

CFY-7735 Restservice: put the edition in the config file

---

cfy_manager/components/cli/cli.py
cfy_manager/utils/certificates.py

This should allow the users to pass a single CA cert/key pair as the input for the installation and distribute the CA cert to the endpoints (UI/CLI). This should make working in HA clusters much simpler for the users.

Sign external certificates with the CA cert/key

---

cfy_manager/components/restservice/restservice.py

cloudify-premium must be installed separately, because it might not
be available (in a community edition)

Restservice: install premium separately

---

cfy_manager/components/nginx/config/rest-location.cloudify

This makes requests to `/api/v3/usersxxx` or `/api/v3/nonexistent` not
proxy to the API at all, and return a 404 instead.

CFY-7559 Return 404 on wrong API URLs

---

cfy_manager/components/nginx/nginx.py
cfy_manager/utils/certificates.py

Instead of passing the CA cert + key (which might not be present)
into the PKCS12 bundle (for riemann to use), provide the internal
cert + key, which is enough for clojure's http client to validate
the connection.
Note that this is unlike openssl-based clients, which would need
the CA cert, not the server cert itself.

CFY-7656 Generate PKCS12 from internal cert + key

---

cfy_manager/components/manager/manager.py

`/usr/sbin` is not on the PATH if we're not using a login shell, so without this,
eg. `$ ssh centos@manager cfy_manager install` will break because `getenforce`
will not be found

CFY-7926 Use full path for getenforce

---

cfy_manager/components/restservice/config/cloudify-rest.conf

Now that the management API endpoint ip can be different,
it must also be passed separately

CY-96 Add a separate amqp_management_host to rest config

---

cfy_manager/components/mgmtworker/config/cloudify-mgmtworker
config.yaml

because a hard-coded limit of 5 doesn't make any sense.

CY-181: configurable bucket size

---

cfy_manager/components/stage/scripts/restore-snapshot.py

* The restore was deleting the directory /opt/cloudify-stage/conf and then copied the one from the snapshot
* Now the files are being copied from the snapshot directory so existing files are not being removed

CY-244 Fix the restore of stage files

---

cfy_manager/components/restservice/config/authorization.conf

Implemented:
- CY-230 - Add permission for text widget in Manager
- CY-277 - User with tenant role 'operations' does not have access to some widgets

CY-230 & CY-277 

---

packaging/create_caravan.py

It is fine that we will be moving away from Diamond - but until the replacement is GA, we should allow users to use it - since a lot of examples still do, particularly pre-4.3.2.

Adding Diamond to create caravan

---

cfy_manager/components/usage_collector/scripts/collect_cloudify_usage.py

* The default behavior of our storage manager `list` limits the result size to 1000 records
* When using `get_all_results` parameter it ignores this limitation
* When using the `count` function it ignores the limit and returns the number of the records

Fix for getting all the results from the rest client

---

packaging/create_rpm

If your change is not in cloudify premium, so the checkout will default to master branch
instead of failing.

CY-487 : Adding default branch for cloudify premium build

---

packaging/create_rpm

If the branch does not exist, it will cause a failure in the script and will fail the build.
So we need a quieter more check.

CY-487 : Fixing the check of branch in edition repos.

---

cfy_manager/components/nginx/config/nginx.conf

The ciphers included in the `HIGH` nginx category include ciphers that aren't considered `Advanced+` and `Advanced` by OWASP, so I removed those.
The intersection between the ciphers that nginx supports, and the ciphers considered `Advanced+` and `Advanced` by OWASP, ends up yielding 4 ciphers only:
* `ECDHE-RSA-AES256-GCM-SHA384`
* `ECDHE-RSA-AES256-SHA384`
* `ECDHE-RSA-AES128-GCM-SHA256`
* `ECDHE-RSA-AES128-SHA256`

CY-531: only allow ciphers considered Advanced+ and Advanced by OWASP

---

cfy_manager/components/manager/config/cloudify.conf
cfy_manager/constants.py

Using `/run/lock/<subdir>` (or `/var/lock/<subdir>`) is problematic because it requires
`/run/lock` (or `/var/lock`) to already be created. They are created by the out-of-the-box `/usr/lib/tmpfiles.d/legacy.conf`, which means that in order to use them, we must either:
* Name this file lexicographically later than `legacy.conf`; or
* Duplicate the `/run/lock` (or "/var/lock") in this file

CY-546: move run dir to a location independent of legacy.conf

---

cfy_manager/components/rabbitmq/config/cloudify-rabbitmq

`/var/run` is deprecated, should use `/run` instead.

CY-568: removed /var prefix

---

cfy_manager/components/nginx/config/https-external-rest-server.cloudify

Happens due to a change in how nginx handles `return 308` starting version 1.13.0.

CY-570: correct duplicate Location header

---

cfy_manager/networks/networks.py
cfy_manager/networks/scripts/add-networks-to-provider-context.py
cfy_manager/utils/certificates.py

No need for the complex passing info through the master to the replica:
simply create the certs right there on the replica (also added validation
that the CA key is available), and call the cloudify-premium API to add
the network to provider-context.

Support for calling add-networks from a cluster replica

---

cfy_manager/components/nginx/config/rest-location.cloudify

In order to be able to know that the current request is using HTTPS/HTTP.

CY-779 Pass forwarded protocol to the REST service

---

cfy_manager/components/globals.py
config.yaml

I implemented this by adding `endpoint_ip` to `config.yaml`.
The default is `localhost`, which will cause `broker_config.json` and `cloudify-rest.conf` to render `localhost` as the AMQP address — as expected.
This also opens the door for microservices — user will be able to specify a different IP/host for `rabbitmq.endpoint_ip`, and this setting will make it to the relevant config files.

CY-791: Management workers and REST service should connect to RMQ through localhost

---

cfy_manager/components/mgmtworker/mgmtworker.py
cfy_manager/components/mgmtworker/scripts/create-admin-token.py

We need to store an admin token so that the mgmtworker can use it
to resume workflows on restart, and to run scheduled executions

Create an admin API token for the mgmtworker

---

cfy_manager/components/rabbitmq/rabbitmq.py

This makes the documentation in the config.yaml correct when it states that
cluster_members does not need filling in for single brokers.

Support simple single-broker install for non-prod

---

.circleci/cluster/create_certs.sh
.circleci/cluster/manager1_config.yaml
.circleci/cluster/manager2_config.yaml
.circleci/config.yml
cfy_manager/components/nginx/nginx.py
cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
cfy_manager/components/service_components.py
cfy_manager/utils/certificates.py

When joining, the CA cert can be just downloaded from the db, no
need to provide it.
Also, when joining, all the queue details are also received from the db.

CY-1248 Don't require CA on a joining replica

---

cfy_manager/components/restservice/config/authorization.conf

They have the ability to get those values already - by starting
an execution and examining the context (directly or creating an
agent).
This change is making that ability explicit.
With this and accompanying PRs, rabbitmq credentials no longer need
to be stored in cleartext in the operation context.

CY-1043 Allow rabbitmq_tenant_credentials for user & operations

---

cfy_manager/components/composer/composer.py
cfy_manager/components/stage/config/cloudify-stage.service
cfy_manager/components/stage/stage.py

This way, files written by stage will be group-writable, so when they
are replicated by syncthing (which runs as cfyuser), they are still
group-writable and so stage on the replica can write/remove them
(eg. update or remove widgets).

CY-1590 Stage: set umask=0002

---

.circleci/config.yml

Instead of /dev/null, so that it's introspectable via ssh at least.

CI fetch_requirements: redirect logs to file

---

cfy_manager/components/restservice/restservice.py
config.yaml

The license is needed for the first manager anyway, and later ones have been failing if it is supplied.

CY-1628 Don't fail uploading license on cluster

---

cfy_manager/components/composer/composer.py
cfy_manager/components/stage/stage.py

When joining a cluster, don't configure the db, it's already configured

CY-1625 Don't configure stage/composer db if not needed

---

.circleci/cluster/create_certs.sh
.circleci/cluster/manager2_config.yaml
.circleci/config.yml
cfy_manager/components/validations.py
cfy_manager/utils/certificates.py

Put the `-passin` in the command, not in the filename.
Also make the CI actually test this, and generating the internal cert at all.

CY-1796 cert validations: handle key password

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py

* Temp defaults, the uuid of the manager should be taken from a file
that the manager reporter generates.
* The uuid of the rabbitmq_brokers should be taken from the
config.yaml.

CY-1856 Add default node_id values to managers and rabbit tables

---

cfy_manager/components/validations.py

The file is invalid, not the (nonexistent, possibly) password

Fix typo in ssl file validation error message

---

.circleci/cluster/db_config.yaml
.circleci/cluster/manager1_config.yaml
.circleci/cluster/manager2_config.yaml
cfy_manager/components/postgresql_server/config/etcd.conf
cfy_manager/components/postgresql_server/postgresql_server.py
cfy_manager/components/rabbitmq/rabbitmq.py
cfy_manager/components/restservice/config/haproxy.cfg
cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
cfy_manager/components/service_components.py
cfy_manager/components/status_reporter/status_reporter.py
cfy_manager/components/validations.py
cfy_manager/exceptions.py
cfy_manager/utils/common.py
config.yaml

* Change the format of db nodes in the config.yaml, it is a dict
instead of a list and it includes the hostname, ip and node_id of a db node.
* Change the format of rabbit nodes in the config.yaml, add node_id and move
the networks under 'networks' key.
* Insert the db nodes info to the DB.
* Set the hostname of the db and rabbit nodes in all-in-one manager to be the
hostname of the manager.
* Take the manager node_id from the config of the reporter.
* Set the node_id of the db and rabbit nodes in all-in-one manager to be the
node_id of the manager.
* If it is not all-in-one and there is no node_id configured in the rabbit nodes
section, we assume it is an external rabbit (user-provided).

CY-1872 Add node_id for Rabbit and Postgres nodes in the config

---

cfy_manager/components/mgmtworker/mgmtworker.py
cfy_manager/utils/install.py
cfy_manager/utils/node.py

* Fix for the community build. The status reporter is not installed in
community, so the config file does not exist and the node_id
is not being generated.
* The node_id will be 'COMMUNITY' constant in this case.

For community edition, node_id will be constant string

---

cfy_manager/components/mgmtworker/scripts/create-admin-token.py

It needs to be actually an empty string (well, or any falsy value), not /dev/null

CY-1981 create-admin-token.py: make sure logging is disabled

---

cfy_manager/main.py

So that we can use cfy_manager to start/stop/restart a single
service, as a facade for systemd (+sudo)

CY-1893 Add a filter list for `cfy_manager restart <service>`

---

cfy_manager/main.py

Deprecating the flag for now. It will do nothing other than print a warning.
To be discussed which version it will actually be removed in.

CY-1989 Deprecate the `--force` flag

---

cfy_manager/components/rabbitmq/rabbitmq.py
config.yaml

Using `localhost` is no bueno because that might/will not be on the
cert usually.

CY-2032 Rabbitmq: use address from networks for contacting mgmt api

---

cfy_manager/components/rabbitmq/rabbitmq.py

Resolve the default network address before putting it in hosts,
because hosts must have actual IPs

Rabbitmq: put only IPs in /etc/hosts

---

cfy_manager/components/postgresql_server/config/etcd.conf
cfy_manager/components/postgresql_server/postgresql_server.py

LISTEN_ADDR need to be IPs because they are used for bind()

CY-2034 etcd: use IP, not addrs, for listening

---

cfy_manager/components/postgresql_server/postgresql_server.py
cfy_manager/utils/certificates.py
cfy_manager/utils/network.py

pg_hba requires either a name, "ip/32", or "ipv6/128", but "name/32" is invalid

CY-2035 postgresql_server: format pg_hba addresses

---

cfy_manager/utils/common.py

No reason to examine the host, the other two parts of the check are
enough.
Examining the hostname breaks if using certificates that don't have
localhost on them

CY-2040: manager_using_db_cluster: don't check host name

---

cfy_manager/components/postgresql_server/postgresql_server.py
cfy_manager/main.py

This actually requires it to become synchronous first, so it's not as
terrifyingly unsafe as it sounds.

CY-2071 Support changing db node to async

---

cfy_manager/main.py

* Add json option to `cfy_manager node get-id` command.
* It will be easier for scripts to parse the return value.

CY-2109 Add json option to get node_id command

---

cfy_manager/components/restservice/restservice.py

Manager status reporetr is not installed in Community so no need to
fetch it's token.

Fix cfy_manager configure in Community version

---

cfy_manager/components/postgresql_server/postgresql_server.py
config.yaml

With some default settings that are mostly based on the minimum requirement
of a 4GB machine for a (AIO) manager

CY-2136 Postgres: add overrides for some basic settings

---

cfy_manager/status_reporter/status_reporter.py

Starting it makes a dependency loop with the ipsetter as well
(ipsetter runs before status-reporter, so when in the ipsetter script we
attempt to do this, status-reporter can't start, because ipsetter didn't exit yet,
because it's waiting for the status-reporter to restart)

CY-2222: no starting status reporter in ip-setter

---

cfy_manager/components/restservice/config/authorization.conf

* By mistake only sys-admin had access to the GET cluster-status
endpoint.
* Now also manager, user and viewer roles have access.

CY-2224 Add permissions for GET cluster-status

---

cfy_manager/utils/users.py

Since group add has been made to work even if the group already exists,
we don't need to check if the group exists before calling it.

Remove redundant group existence check

---

cfy_manager/components/status_reporter/status_reporter.py
cfy_manager/components/status_reporter/supervisord.conf
cfy_manager/status_reporter/status_reporter.py
cfy_manager/utils/service.py

- Unify the service name
- Default to using supervisord to allow things like
`cfy_manager status_reporter start` to use it as well without
having to parse the config

CY-2089 Make status-reporter work under supervisord

---

cfy_manager/components/postgresql_server/postgresql_server.py
config.yaml
setup.py

Setting default PostgreSQL runtime parameters: `shared_buffers` and
`effective_cache_size` basing on machine RAM size:                                                   
* `shared_buffers`: 25% of total RAM size,                                                          
* `effective_cache_size`: 25% for all-in-one manager installation, 50% for cluster installation                                                                       
For all-in-one installation those values might be overwritten in `config.yaml` (`postgresql_server.config.shared_buffers` and `postgresql_server.config.effective_cache_size`).                                                    
Currently it is not possible to overwrite those for cluster installations.

CY-2207 Configure PostgreSQL based on machine RAM

---

packaging/docker/Dockerfile

5672 is not used, because rabbit is always using the SSL 5671

Dockerfile: remove unused port

---

config.yaml

A low-utilisation manager (such as those used for dev and testing) will work
with the specified amount of RAM.

Reduce minimum required RAM

---

.circleci/config.yml
packaging/install_rpm.spec

Instead of pex, install a virtualenv in the rpm the same way we do
for all component rpms

CY-2378 Build the rpm without using pex

---

cfy_manager/_compat.py
cfy_manager/components/postgresql_server/postgresql_server.py
cfy_manager/exceptions.py
cfy_manager/utils/files.py
cfy_manager/utils/node.py
packaging/create_caravan.py
setup.py

Since ruamel.yaml is used all over the code, we have decided to get rid of PyYAML and stick with the single YAML loader/dumper package.

CY-2469 Drop PyYAML in favour of ruamel.yaml

---

cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py

the data is unicode, write it using tempfile's unicode api

create_tables_and_add_defaults: the cert contents isn't bytes

---

cfy_manager/main.py

If restart delegates to start/stop, then each one of them calls
`_prepare_execution` and pushes to the global components list.
That results in everything happening 3 times.
Instead, just call those things directly.
I still need to refactor that damn component management stuff,
but not right now, after all.

CY-2802 cfy_manager restart: only restart service once

---

cfy_manager/components/amqp_postgres/amqp_postgres.py

Missed this in the other pr.
This is actually important, because starting amqp-postgres
(during configure) also starts rabbitmq. Which costs on the order
of 10 seconds.

amqp-postgres: move starting to the start method

---

cfy_manager/main.py

"More important services first" means that you can still
get a mostly-working manager, even if one of the less-crucial
services fails installing

Reorder services: put mgmtworker before composer

---

cfy_manager/main.py
packaging/docker/Dockerfile
packaging/docker/starter.service
packaging/docker/starter.sh

Instead of the .sh that guesses the ip, it's nicer when it's
on the python side. Also, this will allow us to just use it
in the openstack image as well, instead of having to copy
the .sh over there as well.

CY-2841 Move the starter service to the python side

---

cfy_manager/main.py

As opposed to the constant, which is the string "public_ip". Whoops.

image-starter: default the public ip to the private ip

---

packaging/install_rpm.spec
packaging/jenkins/build_rpm.groovy
packaging/jenkins/rpm_builder/Dockerfile

We can use this in jenkins, instead of writing the job
configuration there. It's better to have scripts like this in
source control.
This is using a locally-built docker image for building the
rpm, instead of the rpmbuild/centos7 image, because:
1) the rpmbuild/centos7 image insists on running as a specific
username/uid, and jenkins insists on running things as a different
uid. So we `-u root` and run as root inside of the container instead
2) that image is not very official, and is not maintained by rh

Add a jenkins pipeline for building the main rpm

---

.circleci/cluster/db_config.yaml
.circleci/cluster/queue1_config.yaml
.circleci/cluster/queue2_config.yaml
cfy_manager/components/nginx/config/cloudify.conf
cfy_manager/components/nginx/config/redirect-to-monitoring.cloudify
cfy_manager/components/nginx/nginx.py
cfy_manager/components/prometheus/config/postgres_exporter.service
cfy_manager/components/prometheus/config/prometheus.yml
cfy_manager/components/prometheus/config/supervisord/postgres_exporter.conf
cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/sources.py

Configure Prometheus(es) running on Manager nodes to scape data from the Prometheuses running on RabbitMQ and PostgreSQL nodes.

CY-2859 Prometheus federation configuration

---

cfy_manager/components/components_dependencies.py
cfy_manager/components/sanity/blueprint/bp.yaml
cfy_manager/components/sanity/blueprint/plugins/sanitycheck/sanitycheck.py
cfy_manager/components/sanity/blueprint/plugins/sanitycheck/setup.py
cfy_manager/components/sanity/sanity.py
cfy_manager/components/sources.py

No point in using ssh. We are testing ssh? Then we're not testing other methods.
What's the added value by testing ssh? None, really.
Tbh, we mostly only want to check that workflows are able to run, and that agents work.
So, instead of running the sanitycheck via ssh, run it locally. Makes it a lot faster,
and has WAY less requirements.

Sanitycheck: use a locally-installed agent

---

.circleci/cluster/manager1_config.yaml
.circleci/cluster/manager2_config.yaml
cfy_manager/components/cli/cli.py
cfy_manager/components/restservice/config/supervisord/haproxy.conf
cfy_manager/components/sanity/sanity.py
cfy_manager/main.py
cfy_manager/utils/common.py
packaging/docker/Dockerfile
packaging/docker/supervisord.conf
packaging/supervisord/Dockerfile

Implement a command that runs the configured service management system
(systemd or supervisord) so that we can just use this command and not have
two separate dockerfiles

docker images: implement `cfy_manager run-init`

---

cfy_manager/components/prometheus/config/prometheus.yml

The `host` labels are applied to `prometheus`, `postgresql` and `rabbitmq`
Prometheus jobs.

CY-3137 Add `host` labels to Prometheus scape_configs

---

cfy_manager/logger.py
cfy_manager/main.py

- make the systemd wait return 1 on errors
- show the useful log in the supervisord wait
- refactor the thing to have a common while loop
- carefully consider the logs to show the tracebacks nicely in wait-for-starter

Refactor wait_for_starter

---

cfy_manager/main.py

The current printout is in awkward places. Anyway, there's just
two ways the user is going to do an unconfigured or semi-configured
install, and that's `cfy_manager install` when installing from
a rpm, or `cfy_manager wait-for-starter` when waiting on a container.
And in those cases, tell the user their password.
Other cases, such as `cfy_manager configure`, are useless
Also, if we want to print to screen, just print it, no reason for
the stupid logs/level/handlers dance

CY-3235 Print out admin credentials after installation

---

cfy_manager/main.py

After a test failure: cfy_manager dbs add: error: the following arguments are required: -i/--node-id

Do not require node-id, it is no longer a thing

---

cfy_manager/components/nginx/nginx.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/validations.py

If they are to be removed that can be done by a user.
If they're left, they're an obstacle to cfy remove && cfy install
giving the same system that was originally installed.

Don't alter passwords in config file

---

packaging/install_rpm.spec

This is so that cfyuser can access the rabbitmq key, which is so that mgmtworker
can put it in a snapshot, in snap-create.

CY-3357 Add cfyuser to the rabbitmq group

---

cfy_manager/components/postgresql_server/postgresql_server.py

During PostgreSQL server installation symlinks in /usr/sbin are generated
for PG_BINS.  Those were not removed during removal (`cfy_manager remove`).
This patch fixes that.

CF-3151 Remove postgres bin links

---

cfy_manager/components/validations.py

`sudo` command throws `ProcessExecutionError` not `subprocess.CalledProcessError`. https://github.com/cloudify-cosmo/cloudify-manager-install/blob/76ecdd80b68414d6023a34c9a232aca486eccf07/cfy_manager/utils/common.py#L83. 
Only if it was Java...

Fix error catch in validations

---

cfy_manager/components/sanity/blueprint/bp.yaml
cfy_manager/components/sanity/blueprint/plugins/sanitycheck/sanitycheck.py

A `delete` step was added in sanity-check blueprint.  It mimics
the `cloudify_agent.installer.LocalInstallerMixin.delete_agent` behaviour
by calling `cfy-agent daemons delete` on the specific node and then removing
the runner associated with the agent.

Add agent uninstall in sanity-check

---

cfy_manager/components/postgresql_server/postgresql_server.py

In the case of running `cfy_manager remove` on a postgresql instance, the patroni_startup_check service is not removed. This PR fixes it.

Remove service patroni-startup-check

---

cfy_manager/main.py

Adding `version` flag to `cfy_manager` commands in order to get the Cloudify version. Currently, the only option to get the version is by running `cfy --version` but this wouldn't work on PostgreSQL and RabbitMQ instances as they don't have the Cloudify CLI installed.

CY-3537 Adding version flag to cfy_manager

---

cfy_manager/main.py

When running the command `cfy_manager dbs list` the error: `KeyError: 'services_to_install'` is thrown. This happens because of the new code I inserted to the function `_validate_components_prepared` that tries to call `config['services_to_install']` before the config object is loaded.  This can be seen [here](https://github.com/cloudify-cosmo/cloudify-manager-install/blob/233accbcb07f1c5f36723e263202698049edc6b0/cfy_manager/main.py#L369-L371).
Of course, this issue should be solved in all other places in the `main.py` file.

CY-3573 Fix services-to-install key-error

---

cfy_manager/config.py

If some services are already installed, default the service
list to that. This is so that if you first install some services,
and then run `cfy_manager configure`, then you don't need to
provide services_to_install, because it will be defaulted to
what you already installed.
The list is still overridden by the config.yaml, as before.

CY-3581 Default services_to_install to services already installed

---

cfy_manager/components/cli/cli.py

The CLI removal process fails due to a wrong command that runs: `cfy sudo -u root profiles delete <profile_name>` https://github.com/cloudify-cosmo/cloudify-manager-install/blob/4e45e27e012cbfcedb42215b51115bc4aa06354f/cfy_manager/components/cli/cli.py#L112-L113

CY-3620 CLI removal fails

---

cfy_manager/components/mgmtworker/config/cloudify-mgmtworker
cfy_manager/components/mgmtworker/config/supervisord/cloudify-mgmtworker.conf
cfy_manager/components/mgmtworker/mgmtworker.py

This drops the arguments that stopped being used due to
cloudify-cosmo/cloudify-manager#2379

CY-3611 Mgmtworker: drop unused arguments

---

cfy_manager/components/postgresql_server/postgresql_server.py

Instead of calling etcdctl directly, use the utility method that
we already have.
That method will make sure to use the configured db IPs instead
of hardcoded 127.0.0.1.
This allows running `cfy_manager dbs list` if the etcd cert
(= the postgres cert) doesn't have 127.0.0.1 on it

CY-3627 dbs list: _etcd_command for cluster-health

---

cfy_manager/components/postgresql_server/postgresql_server.py

When installing Cloudify again on the same instance after a failed installation was removed, the installation process fails as it tries to create symlinks that already exist. This PR fixes it by deleting the symlinks if they already exist during installation.

CY-3673 Remove existing postgresql symlinks

---

cfy_manager/main.py
cfy_manager/utils/files.py

This PR fixes the issue of removing a failed Cloudify installation. It does so by:
1. Creating the ./installed/packages.yaml and .installed/components.yaml files before running yum install and installing the components respectively. 
2. For validating that all main services were really uninstalled, the code checks that there are no packages installed for each main service. This is instead of checking if there are no installation files since if the installation process failed, none of the installation files wouldn't have been created.

CY-3662 Fix remove after error

---

cfy_manager/components/nginx/nginx.py
cfy_manager/utils/certificates.py

Currently, if you would try to install Cloudify on a previously installed instance and provide new certificates, the internal and external certs won't be updated. This PR fixes it by implementing a new logic: 
Remark: "certificates" means internal-certificate or CA certificate
```
If the certificates were provided:
If they already exist under /etc/cloudify/ssl:
If the provided certificates and the certificates in /etc/cloudify/ssl are the same:
Do nothing
Otherwise:
Replace them
If they don't exist yet:
Copy them to /etc/cloudify/ssl
If the certificates weren't provided:
If the certificates exist:
Do nothing 
Otherwise:
Generate them
```
This logic will identify whether or not the certificates need to be updated.

RD-322 Update internal and external certs if exist

---

cfy_manager/components/prometheus/config/alerts/manager.yml
cfy_manager/components/prometheus/config/alerts/missing.yml
cfy_manager/components/prometheus/config/alerts/postgres.yml
cfy_manager/components/prometheus/config/alerts/rabbitmq.yml
cfy_manager/components/prometheus/config/prometheus.yml
cfy_manager/components/prometheus/prometheus.py
config.yaml
packaging/prometheus.spec
packaging/prometheus_blackbox_exporter.spec
packaging/prometheus_node_exporter.spec

`scrape_interval` is a [Prometheus configuration parameter](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) which defines how often should Prometheus scrape its targets.
Also used to set up `evaluation_interval` (frequency of rules evaluation).

RD-78 Make scrape_interval configurable

---

cfy_manager/components/prometheus/config/alerts/manager.yml
cfy_manager/components/prometheus/config/alerts/postgres.yml
cfy_manager/components/prometheus/config/alerts/rabbitmq.yml
cfy_manager/components/prometheus/prometheus.py

Add `process_manager` labels to `*_service_*` Prometheus rules.

RD-80 Use Prometheus rules to determine cluster status

---

.circleci/cluster/db_config.yaml
.circleci/cluster/manager1_config.yaml
.circleci/cluster/manager2_config.yaml
.circleci/cluster/queue1_config.yaml
.circleci/cluster/queue2_config.yaml
packaging/docker/config.yaml

Shorten scraping and evaluation interval periods for Prometheus.  This
way a valid response for `cfy cluster status` is going to come faster.

Shorten Prometheus scraping_interval in Docker image

---

cfy_manager/components/nginx/config/rest-location.cloudify
cfy_manager/components/restservice/config/authorization.conf

This PR adds a /labels/deployments rest endpoint to list the tenant's deployments' labels list.
It's related to https://github.com/cloudify-cosmo/cloudify-manager/pull/2458.

RD-478 Create labels endpoint

---

cfy_manager/main.py

`cfy_manager configure` now also starts the services (after #980),
so there's no need to start them again explicitly.
That means the image-starter must only call configure, and can be
made this much simpler.

image-starter: only call `cfy_manager configure`

---

cfy_manager/components/prometheus/prometheus.py

During Prometheus installation HTTP endpoints to be monitored are rendered.  Until now we have used `manager.external_rest_port` to render Cloudify Stage's endpoint, and default (80) port for Cloudify Composer.  This patch changes that as from now on `nginx.port` will be used for both of these.
Also `private_ip` endpoints would be used as http monitoring targets (instead of the mixture of `private_ip` and `public_ip`)

RD-642 Use nginx.port to render composer monitoring target

---

cfy_manager/components/restservice/scripts/update_stored_manager.py
cfy_manager/main.py

When the manager is rebooted and image-starter runs again, run
configure again. That will update the manager with all ip/config
changes.

RD-597 Reconfigure manager on container restarts

---

cfy_manager/components/nginx/config/supervisord/wait_on_restart.conf
cfy_manager/components/nginx/scripts/wait_on_restart.sh

CLI support to control enable/disable ssl using `cfy ssl enable` && `cfy ssl disabled` and also to get the status `cfy ssl status`. On the Manager API side the way how ssl is enabled/disabled is by calling [manager.py](https://github.com/cloudify-cosmo/cloudify-manager/blob/master/rest-service/manager_rest/rest/resources_v3_1/manager.py#L75) where the [set-manager-ssl.py](https://github.com/cloudify-cosmo/cloudify-manager/blob/master/packaging/rest-service/files/opt/manager/scripts/set-manager-ssl.py) is update the nignx configuration file to replace http/https files to make it work with/out ssl.
In order to make the changes take effect immediately a restart to nginx is required but this should be done after the caller to the rest api clean up to avoid unexpected results. In systemd this …

RD-419 Update configuration for wait on restart service for nginx

---

cfy_manager/components/validations.py

Passing the cert in `-untrusted` makes openssl look at all certs in that
file when verifying the chain, so it will find intermediaries there.
It will still be verified against the CA.

openssl verify: additionally pass the cert as untrusted

---

cfy_manager/components/prometheus/prometheus.py

There is not much more information from checking the same service (Stage
and Composer) twice: first directly and then via nginx proxy.  Also the
configuration of these services can change (esp. when user decides to
re-generate CA certs or use his/her own certs).  This is why Status
Reporter will no longer monitor `http(s)://example.com/composer` and
`http(s)://example.com/` endpoints.

CYBL-1080 Stop monitoring external endpoints

---

cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
cfy_manager/components/restservice/scripts/get_monitoring_config.py
cfy_manager/components/sanity/sanity.py

The "is manager in db" check is not enough for assuming that we're
in a cluster. Instead, look at how many managers we have, and only
assume we're in a cluster if there's already a manager other than us.
Also rework the db utils to just return the hostnames, instead of
a separate "is hostname in db" and "get count" utils.

RD-673 Refactor the "initialize db" flow

---

cfy_manager/components/restservice/db.py
cfy_manager/config.py
cfy_manager/main.py

Add a flag for `cfy_manager configure` that skips overwriting
the config file, and use it in the implicit `configure` called from
cloudify-starter.
I very much don't like overwriting the config file.

Starter: don't overwrite the config

---

cfy_manager/components/prometheus/prometheus.py

This part of code used to be run only on clusters, but we recently
changed it to be run "if manager is installed", which also includes
AIO.
But before, it didn't run on AIO, and now, it must not run on AIO
either, because then it'll insert `.cluster.nodes` into the config.
Let's change it to check "if manager ONLY is installed", which
will catch both clusters, and also an external-db/external-rabbit
situation as well, which we want to monitor too

RD-730 Prometheus update_config: not on AIO

---

cfy_manager/networks/scripts/update-manager-networks.py
cfy_manager/scripts/update-admin-password.py

This change added in order to make sure that any script call flask app outside the rest service must call [load_configuration](https://github.com/cloudify-cosmo/cloudify-manager/blob/master/rest-service/manager_rest/config.py#L142) after the flask app is setup or inside the flask app context as the some method like [_find_db_host](https://github.com/cloudify-cosmo/cloudify-manager/blob/b78ba2931783acf76bcbf44d6154389022df4165/rest-service/manager_rest/config.py#L329) used that current app and in case any script tries to call `config.instance.load_configuration()` before setup the flask app it will fail with the following error
```
config.instance.load_configuration()
File "/opt/manager/env/lib64/python3.6/site-packages/manager_rest/config.py", line 147, in load_configuration …
```

RD-793 scripts: load config in app context

---

cfy_manager/components/restservice/scripts/replace_certs_on_db.py

Currently, the replace certificates procedure is failing with the following error: 
`RuntimeError: Working outside of application context.`. 
This happens due to [this line](https://github.com/cloudify-cosmo/cloudify-manager/blob/master/rest-service/manager_rest/config.py#L329) that tries to get the current app but fails. 
In order to prevent it, we pass to [load_configuration](https://github.com/cloudify-cosmo/cloudify-manager-install/blob/master/cfy_manager/components/restservice/scripts/replace_certs_on_db.py#L48) the parameter `from_db=False`, and then it doesn't reach this code.

RD-742 Fix replace certificates script

---

cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/restservice/scripts/get_monitoring_config.py

Overwriting the config is no bueno.
Make a function that returns the required data right there,
instead of tunneling it through the global config.
See each commit.

RD-821 monitoring: stop overwriting the config

---

cfy_manager/main.py

prometheus config changed a lot between 5.1.0 and 5.1.1,
so upgrade must reconfigure it, otherwise we just get "Fail"
outputs in status

cfy_manager upgrade: reconfigure prometheus

---

cfy_manager/components/globals.py
cfy_manager/main.py

Some of the Prometheus configuraiton files use constants.monitoring_port
which must be set before rendering them.

Set global contants before upgrading Prometheus

---

cfy_manager/components/globals.py
cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/restservice/scripts/get_monitoring_config.py
cfy_manager/main.py

Currently, when running `cfy_manager upgrade` on a cluster, it finishes with an unhealthy cluster status. This happens because of two reasons: 
1. On a 3 nodes cluster, the `postgres_exporter.service` configuration is wrong - instead of 
`Environment="DATA_SOURCE_NAME=postgresql://cloudify_db_monitoring:c10udify_db_monitoring@localhost:5432/postgres?sslmode=disable"`, 
there should be  
`Environment="DATA_SOURCE_NAME=postgresql://cloudify_db_monitoring:c10udify_db_monitoring@172.12.0.16:5432/postgres?sslmode=verify-full&sslrootcert=/var/lib/patroni/ca.crt"`.
This is fixed by setting `POSTGRESQL_SERVER[ENABLE_REMOTE_CONNECTIONS]` to `True` in [`_apply_forced_settings`](https://github.com/cloudify-cosmo/cloudify-manager-install/blob/635cba4726258d24c5f603f2261273e5de385015/cfy_manager/compon …

Fix upgrade in cluster mode

---

packaging/docker/Dockerfile

It's needed for some of our getting started examples.

RD-871 Include openssh-clients in docker image

---

cfy_manager/components/base_component/base_component.py
cfy_manager/components/composer/composer.py
cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/stage/stage.py
cfy_manager/main.py

* Re-configure Stage component upon upgrade
* Re-configure Composer component upon upgrade
* Re-configure UI before stopping DB
During the upgrade procedure re-run UI components configuration when
database service is still running.  This is because database service is
required for the configure() functions of Stage and Composer components.
* Add extra function for upgrading components
* Prometheus().upgrade() implementation
* Stop the components in revesed order
It might be a good idea to stop the services in reverse order from how
they are setup/started.  Mainly due to their dependencies (on db service
mostly).

Run components' upgrade functions on upgrade (#1036)

---

cfy_manager/components/restservice/scripts/update_stored_manager.py

Correctly update the stored rabbitmq, updating the `.management_host`
as well.
This fixes the "stop and restart a container with a different IP" flow.
Without this, restarting the container with a different ip, fails in the
restservice stage.

RD-1062 update_stored_manager: fix updating broker

---

cfy_manager/components/restservice/scripts/update_stored_manager.py

DB and broker might not be there, because they can have different
hostnames than the manager. Which is obviously the case in a
cluster.
The code already has `if broker` etc, we just need the .get
to return None rather than throw.

RD-1321 update-stored-manager: cope with clustered managers

---

cfy_manager/components/restservice/config/authorization.conf

This PR adds permissions for the new Deployments View widget
See [RD-1222](https://cloudifysource.atlassian.net/browse/RD-1222)
The permissions are the same as for the regular deployments widget.

RD-1222 Add permissions for Deployments View widget

---

cfy_manager/components/cli/cli.py
cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/scripts/update_stored_manager.py
cfy_manager/main.py

We have the technology! No need for clean-db!
This way, the `configure` that runs after manager/container restarts, will
be able to
1. run without touching the password if not provided,
2. change the password if the config changed.
And anyway, changing the password in the config is a thing that the user
can do, so it would be good if we handled it properly, as opposed to just
telling the user "sorry no can do, you have to drop your db".

RD-1858 Allow `cfy_manager configure` to change the password

---

cfy_manager/components/cli/cli.py
cfy_manager/utils/common.py

Instead of always `cfy prof use`, make a single profile with a constant name,
and `cfy prof set` it with the changed values.
Also see the jira for additional details, and see the commit messages as well.

RD-1867 CLI: use and update a single profile

---

cfy_manager/components/restservice/config/authorization.conf

It is necessary to set permission (RD-1846) for who is able to see Getting Started Model (developed as RD-1442).
This PR adds `sys_admin` role in the `authorization.conf` file for Getting Started Model.
Task: https://cloudifysource.atlassian.net/browse/RD-1846

RD-1846 - added permissions for sys_admin to has access to Getting Started Model

---

packaging/docker/Dockerfile

Because of https://nvd.nist.gov/vuln/detail/CVE-2021-3156, let's use patched sudo RPM published by https://www.sudo.ws/.

RD-1908 Use patched sudo version 1.9.6

---

jenkins/Jenkinsfile
jenkins/build-pod.yaml

This is for the container that runs `cfy`.
This is because cfy 5.1.2 can't be installed on py2 just like that (anymore),
due to networkx 1.9.1 requiring `decorator>3.4.3`, which just upgraded
to 5.0.0, which isn't py2-compatible.
So it's either pin decorator here, or just switch to py3. Switching to py3
is preferred.
Also clean up some jq usage.

use a py3.6 container for the cfy infra

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py

We add predefined system filters so they can be used by the UI widgets.
This is Ofer's description of them:
> system filters are going to be used as the default value for a widget. for example: we will be using the new "deployments" widget in two different pages, one will be the environments page which will use the deployments widget filtered by "environments", and the services page will use the same widget, this time using the "services" filter.
> The filters will be available in the DB and the users should not be able to delete or modify them.
> The widget settings (edit mode for the widget) will include a "filter" setting and the out-of-the-box installation of cloudify will have the system filters as the default.

RD-1869 Add predefined system filters

---

cfy_manager/components/prometheus/prometheus.py

In case of an upgrade from previous installation of cloudify-manager,
let's not re-render Prometheus configuration files.
This is because an upgrade of the cloudify-manager should not modify
the configuration of its components, rather upgrade the software itself.
In case of a direct requirement for a change, it should be handled by
the RPM file itself.

RD-2084 Don't rerender Prometheus configuration on upgrade

---

cfy_manager/components/restservice/db.py

In the case of an external DB connection, like Azure DBaaS, `cloudify_username` is defined as `<database_username>@database_name>`. This PR handles this case.

RD-2065 Fix three nodes cluster with external DB

---

cfy_manager/components/restservice/db.py

Reverts cloudify-cosmo/cloudify-manager-install#1120
This shouldn't have gone into the 5.1.2 branch, but  into.. some other branch

Revert "RD-2065 Fix three nodes cluster with external DB"

---

cfy_manager/components/prometheus/prometheus.py

Prometheus' (a.k.a. monitoring service) configuration should not change
with newer releases of Cloudify.  So configuration shall be rendered
only in case of `cfy_manager configure` (and not `cfy_manager upgrade`)

RD-2084 Do not re-configure Prometheus at all on upgrade

---

cfy_manager/components/prometheus/prometheus.py
cfy_manager/utils/files.py

* Get rid of upgrade parameter
Since we're not running configure() on Prometheus.upgrade(), the
parameter is unnecessary.
* Update manager services alerts while upgrading
In case a new version of Cloudify has a different set of manager's
services running, let's update it during the upgrade process.

RD-2084 Prometheus config upgrade

---

cfy_manager/components/restservice/db.py

Currently, the system filter `csys-service-filter` filter rule is `csys-obj-type!=environment`. This means that if a user attaches a label to a deployment with the key `csys-obj-type` with any value different from `environment` (not necessarily `service`), it will be returned too. 
To solve this we need to change the filter rule to be `csys-obj-type=service`.

RD-2035 Modify csys-service-filter

---

config.yaml

A manager generally either needs a lot more than 5GB or a lot less.
Therefore, this validation isn't massively valuable. I've set it to
1 so that we validate there is some space left to at least install
one basic blueprint.

Lower disk space validation value

---

cfy_manager/components/restservice/db.py

The `is_not` operator was created especially for this task. We would like the services' system filter to capture all the deployments that have a label with key `csys-obj-type` and value other than `environment`, or don't have a label with the key `csys-obj-type` at all. This is done using the `is_not` operator. 
FYI, @Gelio

RD-2146 Using is_not operator in services system filter

---

cfy_manager/main.py

Replace certificates relies on the hostname, which does not behave as the
config.yaml comments suggest it does unless set_globals is called.

RD-2292 Use set globals when replacing certs

---

cfy_manager/components/restservice/config/authorization.conf

This ports #1154 to 6.0.0
That is used for exec-groups PATCH, for setting target groups

RD-1419 Add the execution_group_update permission, 6.0.0

---

cfy_manager/components/prometheus/prometheus.py

Use the manager's `private_ip` address to render `rabbit_missing.yml`
Prometheus' alert configuration in case `rabbitmq_nodes` are not
configured (e.g. AIO installation).

RD-2419 Use private_ip as rabbitmq host for AIO installation

---

cfy_manager/components/nginx/nginx.py

Currently, we try to generate the external certificate from the internal CA cert and key, but don't verify they indeed exist. This PR fixes it.

Generate the external certs from the internal CA only if it exists

---

cfy_manager/components/prometheus/prometheus.py

Without this, prometheus seems to hang on uninstall somewhat frequently
on a three node cluster.

Don't race to hang when uninstalling clusters

---

cfy_manager/main.py
jenkins/Jenkinsfile

This PR fixes the removal of a single service from a manager that uses the cfy-installer image (more about it in the [JIRA](https://cloudifysource.atlassian.net/browse/RD-2464)). 
The fix includes the following:
- The packages.yaml file includes all main services as keys, and the value of each service is a list of the packages related to it. Following this PR, in case the config.yaml file includes `monitoring_service` and `enrotpy_service`, their related packages will be appended to each list of a main service (manager, database, queue). The logic behind this is that if the user installed these services (entropy and monitoring), it doesn't matter if they didn't put them in the config.yaml file they used for configuration - they are installed. 
- Simplifying the `_get_items_to_remove` …

RD-2464 Refactor installation files

---

cfy_manager/components/postgresql_server/postgresql_server.py
cfy_manager/components/rabbitmq/rabbitmq.py
cfy_manager/utils/db.py
cfy_manager/utils/network.py

* Factor out `_ip_to_identifier` function.  The function makes nice
identifiers based on both IPv4, IPv6 and also hostname-based
addresses, e.g. `10.10.10.10` becomes `10_10_10_10`, `fe80::1`
becomes `fe80__1` and `example.com` becomes `example_com`.
* Use `ipv6_url_compat` instead of manually formatting IPv6 into URL.
This makes for a slightly slower code, but the code becomes less
bug-prone and maybe also readable.
* Factor out IPv6 enabled check for RabbitMQ installation
* Cleaner postgres_host partitioning into host:port
* Use `ipaddress` package to detect IPv6 address instead of using
`socket.inet_pton()`

RD-2522 IPv6 fix-ups

---

cfy_manager/components/restservice/db.py
config.yaml

… which marks RabbitMQ service as external.

RD-2621 Introduce `rabbitmq.is_external` config flag

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
cfy_manager/components/restservice/scripts/update_stored_manager.py

`monitoring_username` and `monitoring_password` columns for manager, db and rabbit nodes are no longer necessary.  Instead we use the same credentials across all of the the Prometheus' federated nodes.

RD-2621 Drop monitoring credentials

---

cfy_manager/utils/install.py

This was necessary because removing postgresql doesn't also remove its dependency postgresql-libs, which can botch a later cloudify RPM upgrade on the same machine

RD-2754 Add autoremove to teardown to also remove unused dependencies

---

cfy_manager/config.py

It happens on pretty much every run, so it really doesn't need to be so dramatic.

Don't warn when using sudo to access yaml files

---

cfy_manager/components/nginx/config/rest-proxy.cloudify
cfy_manager/components/restservice/scripts/restservice-wrapper-script.sh

Add `X-Cloudify-Audit-*` response header values to gunicorn-access.log.
Make the file easier to read.

RD-2756 Log X-Cloudify-Audit-*

---

cfy_manager/components/rabbitmq/rabbitmq.py

chown because otherwise file is (sometimes) not readable producing errors:
```
inet_config: file /etc/rabbitmq/erl_inetrc not found
File operation error: eacces. Target: /etc/rabbitmq/erl_inetrc. Function: get_file. Process: kernel_sup.
```

WDR-79 chown rabbitmq:rabbitmq /etc/rabbitmq/erl_inetrc

---

cfy_manager/main.py

Jenkins' inte-tests keep timeouting on this. 5 minutes is not enough?!
Fine, here, have 10 minutes.
We should really make this faster, but for today, I want to see the
tests run at all

wait-for-starter: bump timeout to 10 mins

---

cfy_manager/components/postgresql_server/config/supervisord/etcd.conf

The systemd one uses this config file, and we update it in some situations,
so let's just use the same one for both service managements.

RD-3257 Make supervisord etcd use same config

---

cfy_manager/components/restservice/config/authorization.conf

Note that these are useless without access to the hash_secret

RD-2872 Allow admins retrieving password hashes

---

cfy_manager/components/restservice/config/authorization.conf

It's not actually needed now as the endpoint that was going to use it
was changed to use a different approach.

Remove set_plan permission

---

cfy_manager/components/restservice/config/authorization.conf

This is to allow stage to use this endpoint for all users when
displaying things like 'set password'.
It's the same access permissions as ldap_status_get, and should
be about as sensitive.

Allow anyone access to IDP check

---

cfy_manager/components/amqp_postgres/amqp_postgres.py
cfy_manager/components/composer/composer.py
cfy_manager/components/execution_scheduler/execution_scheduler.py
cfy_manager/components/mgmtworker/mgmtworker.py
cfy_manager/components/nginx/nginx.py
cfy_manager/components/postgresql_server/postgresql_server.py
cfy_manager/components/rabbitmq/rabbitmq.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/rsyslog/rsyslog.py
cfy_manager/components/stage/stage.py
cfy_manager/utils/service.py

When uninstalling the cluster, we were leaving several services lying around.
This resulted in problems during reinstall.

CFY-3820 Clean up cluster services properly

---

cfy_manager/components/postgresql_server/config/etcd.conf

Doing so breaks initial cluster setup.

RD-3992 Don't put brackets in etcd node names

---

cfy_manager/utils/db.py

In case remote connections are enabled, we should be talking to
`private_ip`.

RD-3990 DB server address for remote connections

---

cfy_manager/main.py

Because we gave up on saving the configuration file upon finishing
configuration
https://github.com/cloudify-cosmo/cloudify-manager-install/commit/f4a73b5c321c9411ee80968c12d6d51faad0b858#diff-f4fb19e547a01993edd4f655a5df9a8477d8a1b8f386ed50a60e26c0ab84db97
the password to display should no longer be read from the configuration
file, but from the current `config` instance.

RD-4046 Print valid admin's password on exit

---

cfy_manager/components/restservice/config/supervisord/cloudify-restservice.conf

config.yaml does declare extra_env on both restservice and the
mgmtworker, however only the mgmtworker actually renders it.
So make it go into the restservice config as well.
The line is pretty much just copied from the mgmtworker .conf

CYBL-1439 Supervisord: honor config's extra_env

---

cfy_manager/main.py

Eg. `cfy_manager -h` doesn't need root, really.

RD-4215 ensure_root: don't crash-and-burn on empty subcommands

---

cfy_manager/components/stage/config/cloudify-stage
cfy_manager/components/stage/config/supervisord/cloudify-stage.conf
config.yaml

Similar to the mgmtworker and the restservice, extra_env allows
passing envvars to stage, most notably proxy settings

RD-4188 Use extra_env for stage

---

packaging/docker/Dockerfile

In #1139, we disabled ssl for dockers, by changing the default
config.yaml - but in #1258 we stopped overwriting the config, so
we need to now change the default-default config.yaml.

RD-4159 docker images: default to no-ssl

---

cfy_manager/components/prometheus/prometheus.py

In case of upgrading a cluster, Prometheus configuration was not properly rendered (`other_managers.yml` was empty).  This patch fixes that.

RD-4352 Update fix for Prometheus

---

cfy_manager/components/restservice/restservice.py

Otherwise upgrade can mangle the config to make restservice not start.

Set config whenever configuring services

---

cfy_manager/components/restservice/config/authorization.conf

They're system level not tenant level, so manager shouldn't have had it by default.

Only allow sys_admin to manage others tokens

---

cfy_manager/components/nginx/nginx.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components_constants.py
cfy_manager/main.py

... because instead of running configure (or install) with --clean-db,
one should rather remove installation with `cfy_manager remove` and only
then run `cfy_manager install`.

RD-4333 Drop `--clean-db` option to `cfy_manager`

---

cfy_manager/components/sources.py
cfy_manager/main.py

If it was already installed, yum will cope by either updating it or
refusing to update it, which doesn't appear to affect the exit code.

RD-4283 Install rsyslog

---

cfy_manager/components/sanity/blueprint/bp.yaml

No reason to keep this pinned to 5.0.5 types

Update the sanity blueprint

---

cfy_manager/components/postgresql_server/postgresql_server.py
cfy_manager/utils/service.py

It broke when is_active started behaving better by returning a bool.

Make is-active work with etcd again

---

cfy_manager/components/cli/cli.py

Heh, the previous impl. ended up returning the empty string, because
the field exists in the default config.yaml, but is, well, empty.
Which led to the one-level-higher using private ip instead of
manager.cli_local_profile_host_name

RD-5562 cli profile hostname: fall back correctly

---

cfy_manager/components/nginx/config/rest-location.cloudify

For now, swagger in restservice is disabled, in
cloudify-cosmo/cloudify-manager#3802
To keep the UI working, use prerendered jsons in the meantime

RD-5683 Use prerendered swagger docs

---

cfy_manager/utils/common.py

Some users want to run the manager with a sudoers settings that
`secure_path` doesn't include `/usr/bin`. And so, then `cfy` is not
on the PATH.
We can just pass the absolute path here.

RD-5747 cli: use absolute path to cfy

---

cfy_manager/components/composer/composer.py
cfy_manager/components/stage/stage.py
cfy_manager/components/validations.py
jenkins/Dockerfiles/test/Dockerfile
jenkins/Jenkinsfile

There's only a few places where we sudo binaries with a non-absolute
path. We can just make them absolute and then we'll work with any
secure_path setting.
And so, in CI, let's actually test that "no secure_path" approach.
Now, we can CI-test stricter images than we normally build.

RD-5747 Don't require any secure_path at all

---

cfy_manager/components/validations.py
config.yaml

Allow validating the env in general, by regexps. Also, include some
default validations for PATH.

RD-5747 Add envvar validations

---

config.yaml

On some images, under sudo, /usr/local/{sbin,bin} isn't on the PATH,
but things seem to work. So it's not required.
Also remove the accidentally duplicated line. No need to check things
twice!

RD-5747 Make the PATH validation less strict

---

config.yaml

In distro, it is named rhel, not redhat.
But actually allow both. I think that's fine too.

supported_distros: allow "rhel"

---

cfy_manager/components/validations.py

`distro.linux_distribution()` is deprecated as of 1.6.0
https://github.com/python-distro/distro/blob/095882f9b4b397085c34c9bbe20ec05263b9e008/src/distro/distro.py#L159

RD-5982 Replace deprecated linux_distribution()

---

cfy_manager/components/composer/composer.py
cfy_manager/components/prometheus/config/alerts/manager.yml
cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/stage/stage.py
cfy_manager/utils/common.py
config.yaml

If we know that the cluster uses some other method of replicating the filesystem, eg. using a shared volume, then there's no point in having syncthing running as well.
This allows a config flag to avoid configuring syncthing in these cases.
If the flag is false:
- syncthing will not be configured & started
- no additional chmods will be applied
- monitoring configuration will not track syncthing's status
By default, replication is still enabled (no change from status quo)

RD-5984 Allow skipping filesystem replication

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
cfy_manager/config.py
cfy_manager/utils/scripts.py

Instead of creating the user+tenant in the script here, use the cloudify-manager module to do it.
Additionally:
- store absolute paths to config files, instead of the current "filenames but in `/etc/cloudify` implicitly"
- rewrite `dict_merge`
I do recommend viewing commits separately

RD-6073 Use configure_manager to create the admin user

---

packaging/files/etc/supervisord.conf

Let's silence all the "service started", "service stopped", "pid reaped" messages. Supervisord on INFO is just way too verbose.

RD-6291 Set supervisord logging level to `warn`

---

packaging/docker-rh8/Dockerfile
packaging/docker/Dockerfile

We don't use 5672, that'd be non-ssl. We always use ssl for rabbitmq.

RD-6289 Dockerfile: correct the rabbitmq port

---

cfy_manager/main.py
cfy_manager/utils/service.py

Improve the "Manager is ready" message shown after a manager has started.
Example output:
```
##################################################
Manager is up at https://172.17.0.2
Admin password: admin
##################################################
To connect to the manager, use:
cfy profiles use 172.17.0.2 -u admin -p admin -t default_tenant -ssl -c path/to/cloudify_internal_ca_cert.pem
##################################################
To install the default plugins bundle run:
'cfy plugins bundle-upload'
##################################################
```
- use "public_ip or private_ip" in case public ip isn't set
- if no ip is detected (eg. in `wait-for-starter`) just show nothing
rather than showing an empty string
- no need for the `logger.notice`, let's only have the print, …

RD-6292 Improve the manager is ready message

---

cfy_manager/components/nginx/config/rest-location.cloudify
cfy_manager/components/restservice/config/authorization.conf

On worker nodes, we can expose the monitoring system behind the manager authentication, so that users can reach it easily.
For inter-cluster communication, the :8009 & separate credentials approach still stays, this just adds a more user-friendly way of getting to prometheus.

RD-6290 Expose `/monitoring` on worker nodes

---

cfy_manager/components/mgmtworker/config/supervisord/cloudify-mgmtworker.conf
cfy_manager/components/mgmtworker/mgmtworker.py

We include a python-3.6 venv in the mgmtworker, with a base for plugin installations.

RD-6082 Additional plugins-base PATH for the mgmtworker

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py

After cloudify-cosmo/cloudify-manager#3961 the permissions & roles are just created in configure_manager.py, based on the config.
So I'll just pass authorization.conf as yet another config file. It'll get merged with the other config.yaml files.
We can do this, because config.yaml currently has no `roles:` and `permissions:` top-level keys.
That also means that you can now override your roles & permissions using just config.yaml. Nifty.

RD-6541 Move creating permissions to cloudify-manager

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py

Move this out of the create_tables.py script, and into the... well, the other script. Now we are going to pass that through. And refactor the passing-through part a bit, too.

Create ProviderContext in configure_manager

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/restservice.py
cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
cfy_manager/components/restservice/scripts/update_stored_manager.py

This is not trivial, and I also refactor a bit, so it's not gonna be very easy to review; sorry about that, but I wasn't able to come up with a better way :)
The point is taking that `_insert_manager` out of
create_tables_and_add_defaults.py, and moving it to the cloudify-manager side.
Alas, that script was also used for inserting a new manager into an already-existing db, in a cluster. cloudify-manager's configure_manager.py can do that as well, and does, but for now I'd like to limit the changes here to a minimum, so I'll still keep a `def insert_manager` here.
But let's use the `update_stored_manager.py` script for inserting it. And so, that `update` now really means `upsert`. So I'm refactoring that script a bit as well.
And restservice.py's `_configure_db` is a bit nicer now as …

RD-6566 Move inserting manager to configure_manager.py

---

cfy_manager/components/nginx/config/rest-location.cloudify

On a 401, redirect to stage login. Nicer than the browser http basic auth popup.

RD-6717 Monitoring auth: redirect to stage on error

---

cfy_manager/components/mgmtworker/config/cloudify-mgmtworker
cfy_manager/components/mgmtworker/config/supervisord/cloudify-mgmtworker.conf
config.yaml

The directory is used for keeping local copies of manager's resources. Currently mgmworker will download deployment working directory before attempting to execute any operations or workflows.  Afterwards it will upload the directory back to the manager.

RD-6614 Configure mgmtworker's resources dir

---

cfy_manager/components/postgresql_server/postgresql_server.py

The PostgreSQL's wal_buffers settings parameter cannot exceed 2097144kB
https://postgresqlco.nf/doc/en/param/wal_buffers/

RD-6448 Limit PostgreSQL wal_buffers value

---

cfy_manager/components/nginx/config/authd-location.cloudify

This functionality is now implemented by /resources/ endpoint.  This is complementary to https://github.com/cloudify-cosmo/cloudify-manager/pull/4018

Drop /file-server-index endpoint

---

cfy_manager/components/rabbitmq/config/rabbitmq.config

Rabbitmq 3.8.15 enables consumer_timeout by default, which means unacked tasks will be rescheduled after 15 (up to 3.8.17) or 30 (later) minutes.
This breaks mgmtworker workflows/operations, which are late-acked.
In order to get pre-3.8.15 behaviour (and note, Cloudify up to 6.4.0 was using rabbitmq 3.8.4), disable this timeout.

RD-6802 rabbitmq: disable consumer_timeout

---

cfy_manager/main.py

Also wait for the systemd starter service too. We don't support systemd ourselves, but some deployments (eg. the AMI) might want to implement their starter service as a systemd unit still.

RD-6807: wait-for-starter: allow systemd service

---

cfy_manager/main.py
jenkins/bp/ec2-manager-install-blueprint.yaml

This ports #1467 to 6.4.2
Some changes were necessary: 6.4.2 does still support using systemd, instead of supervisord.
Thankfully, `_choose_starter_service_poller` will look at both anyway.

RD-6807 wait-for-starter: allow systemd service

---

cfy_manager/components/postgresql_server/postgresql_server.py

It appears there was a race condition previously, probably related to the targeted node taking too long to kick off the restart, meaning that when the sync replica check occurred the old node was still synchronous, leading to the exception being raised.
Let's only error when attempts expire instead.

RD-7008 Stabilise sync replica promotion

---

cfy_manager/components/restservice/db.py
cfy_manager/components/restservice/restservice.py

Instead of relying on RPM scriptlets, let's execute alembic migration in cloudify-manager-install restservice upgrade procedure.

RD-7044 Move db migration to cloudify-manager-install

---

cfy_manager/components/nginx/nginx.py
cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/rabbitmq/rabbitmq.py
cfy_manager/components/validations.py
cfy_manager/tests/test_certificates.py
cfy_manager/utils/certificates.py
jenkins/Jenkinsfile
jenkins/cluster/start_cluster.sh
setup.py

Rewrite the cert-related functions to use cryptography rather than subprocess openssl.
Also add some tests around the cert handling functions.
This doesn't cause any behaviour changes by itself, but will make it MUCH easier to work with certs.
In the commits, I'm going to be essentially rewriting every `openssl`-calling function one by one, to use cryptography instead.

RD-7056 Refactor generating internal/external certs

---

cfy_manager/components/globals.py
cfy_manager/components/nginx/config/manager.upstream
cfy_manager/components/nginx/nginx.py
cfy_manager/components/prometheus/prometheus.py
cfy_manager/components/validations.py
cfy_manager/main.py
cfy_manager/tests/test_certificates.py
cfy_manager/utils/certificates.py

In some cases, the internal cert will be used to host the "public" access as well, so it should include the public ip as well. Also, there's no downside to just putting it on there.
The main thing to note is:
- when public ip is an ip (not a domain name), and we serve https/443 on both "internal" and "external", then we end up using the internal cert for all requests, because SNI only works for domain names, not ips.
And so, let's decide python-side (set_globals) on what exactly should the nginx listeners be, and then use validations to check that the certs are as expected.
This means that with the common auto-generated cert approach, if we enable external ssl, there's only one nginx listener on 443; and if external ssl is disabled, there's one on 80, and one on 443.
...that, plus a whole …

RD-7056 Include public_ip on the internal cert

---

cfy_manager/components/composer/composer.py
cfy_manager/components/stage/stage.py

Those json config files contain the internal REST endpoint's port, so they need to be updated with whatever the configured port is (default 443, old-default 53333).

RD-6586 Use the configured port in stage & composer config files

---

cfy_manager/components/usage_collector/scripts/collect_cloudify_uptime.py
cfy_manager/components/usage_collector/scripts/collect_cloudify_usage.py
cfy_manager/components/usage_collector/scripts/script_utils.py
jenkins/bp/ec2-manager-install-blueprint.yaml

Avoid using the storage-manager, where it's not necessary. Specifically, `sm.count()` no longer exists.
Also, just push appctx at the entrypoint, no need for more fine-grained context management than that.

RND-206 usage-collector: use direct queries where possible

---

cfy_manager/components/globals.py

Don't just add multiple listeners with the same port, use the ones from the list!
Whoops!

nginx listeners: render the configured internal port

---

cfy_manager/components/globals.py
cfy_manager/components/validations.py
jenkins/cluster/create_certs.sh
jenkins/cluster/manager1_config.yaml
jenkins/cluster/manager2_config.yaml
jenkins/cluster/manager3_config.yaml

SNI doesn't work with IPs, only hostnames/fqdns :)
So we can't have multiple IPs in nginx.conf, and have each use a different cert. Therefore, if public_ip is an ip (not hostname), it will have to cope with being served using the internal cert as well... for the user, it shouldn't make much difference, if it's an auto-generated certificate. But if the user tries to provide their own certificate in that case, it's a validation error, because that'll never work.
Also see comments

RND-495 If public_ip is not a hostname, use internal cert

---

cfy_manager/components/nginx/config/manager.upstream
config.yaml

A pretty basic setup of allowing 10 reqs per second per client.
See config.yaml comments for description of the available configuration options.
Execution-token requests are exempt from the rate-limit because we don't want customer's executions to suddenly start failing because their `ctx.logger.info()` spam started receiving 503s...
(And yes, execution-token takes precedence, i.e. if a request contains an invalid execution-token but also a valid authorization header, it's a 401.)

RND-584 nginx: add request rate-limiting

---

cfy_manager/components/postgresql_server/postgresql_server.py

Don't ever use 'trust' for host, even for localhost. When using a network conneciton, always use a password

pg_hba: use password auth for 'host' connections

---

packaging/docker/Dockerfile

With this switch, the UI will not be installed.
...well, it will be uninstalled after installing. We don't want to touch actual code (main.py/sources.py) for this change, just the build infra (here: the dockerfile).
When using this, you should also set skip_installation for stage and composer in config.yaml

Dockerfile: introduce a "lightweight" switch

---

cfy_manager/utils/files.py

In containerized environments, ismount might return True for files, depending on the filesystem. So yeah, files can be mounted as well.
The listdir call will fail for files though, so this must be actually only done for mounts that are also directory mounts

RND-1267 utils.files.remove: handle mounted files

---

cfy_manager/tests/test_certificates.py
cfy_manager/utils/certificates.py
jenkins/bp/ec2-manager-install-blueprint.yaml

See the comment. When generating a test CA, let's try to make sure that many created test CAs don't share the name.

NE-6426 Add a random suffix to test CA cert name

---

packaging/docker-rh8/Dockerfile

Change the way how the glibc langpack and locale-source packages are installed due to issues with building rhel-8 images.

Change the glibc minor version

---

cfy_manager/components/haveged/haveged.py

In case a haveged service is managed by systemd (i.e. not Cloudify/supervisord), do not attempt to stop it using supervisorctl.

NE-12156 Do not attempt to stop systemd haveged
