cloudify-cosmo/cloudify-manager-install

- cfy_manager/components/manager/manager.py
Just assume that SELinux is not enforced and carry on
> Don't break if the `getenforce` command is not available

- cfy_manager/main.py
Without resetting the DB, we'd need to have a whole separate path for
updating the DB, config files, etc.
This solves this problem
> CFY-7725 Only allow using --admin-password if passing --clean-db

- packaging/create_rpm
This will allow for better error handling
> create_rpm: use threading instead of multiprocessing

- cfy_manager/components/restservice/config/cloudify-rest.conf
- cfy_manager/components/restservice/restservice.py
- cfy_manager/components/usage_collector/scripts/collect_cloudify_usage.py
Related to cloudify-cosmo/cloudify-manager#1140
> CFY-7735 infer edition from cloudify_premium package import

- cfy_manager/utils/certificates.py
> CFY-7656 Fix create-pkcs12 logging

- cfy_manager/components/rabbitmq/config/cloudify-rabbitmq
- cfy_manager/components/rabbitmq/rabbitmq.py
- config.yaml
Related to cloudify-cosmo/cloudify-manager#1193
> CFY-7899 Add RABBITMQ_NODENAME to rabbitmq's env file

- cfy_manager/components/influxdb/config/logrotate
- cfy_manager/components/influxdb/influxdb.py
It is already deployed by the amqpinflux RPM
> Influxdb: remove logrotate script

- config.yaml
See steps to reproduce in [CY-141](https://cloudifysource.atlassian.net/browse/CY-141) for details.
> CY-141 Add `flask_security` to config.yaml

- cfy_manager/components/globals.py
The encryption key is being used to encrypt the secret's value
> CY-197 Add the encryption key to the security config

- cfy_manager/utils/certificates.py
In case the internal cert is a bundle, we must extract the server
cert from it, and use that. We can't create pkcs12 files from
a whole bundle, a single cert is required.
> create_pkcs12: extract cert from a bundle

- packaging/create_rpm
Now only once the relevant repo will be cloned
> CY-166 : Fixing that fetch repo stage

- cfy_manager/components/cli/cli.py
This reverts commit 932c6e5bff3194b0889287b4644e183cef3d51bd.
> Revert "CY-506: don't skip validation"

- packaging/create_rpm
- We only need the return reslut not the log from git
> CY-487 : Suppress git failure logs commands

- cfy_manager/components/cli/cli.py
This reverts commit 7ed449e779de577e7345593b2564c8915b9aa727.
> CY-506: don't skip validation

- cfy_manager/components/cli/cli.py
- cfy_manager/components/globals.py
- setup.py
> CY-471: updating jinja2

- cfy_manager/components/mgmtworker/mgmtworker.py
> CY-696 Don't overwrite hooks.conf file if it exists

- cfy_manager/components/composer/composer.py
- cfy_manager/components/globals.py
- cfy_manager/components/stage/stage.py
- cfy_manager/encryption/encryption.py
- cfy_manager/main.py
https://cloudifysource.atlassian.net/browse/CY-731
https://cloudifysource.atlassian.net/browse/CYBL-622
> Update encryption key for AES256

- config.yaml
> CY-874 Resolver fallback: set default to true

- cfy_manager/components/restservice/db.py
- cfy_manager/components/restservice/manager_config.py
- cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
- cfy_manager/constants.py
They are now created in the migration
> Only update, not insert, config entries

- cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
Can't load it before it's created...
> Create db: don't load config from db yet

- cfy_manager/components/base_component/base_component.py
- cfy_manager/components/globals.py
- cfy_manager/components/rabbitmq/rabbitmq.py
- cfy_manager/components/validations.py
- cfy_manager/constants.py
- cfy_manager/utils/certificates.py
This was not happening where the queue was not being installed otherwise.
> Move rabbitmq CA to correct location

- cfy_manager/components/restservice/config/authorization.conf
They already have tenant_rabbitmq_credentials!!
> authorization.conf: allow tenant_get for user & operations

- cfy_manager/components/restservice/restservice.py
No reason to use the blueprints endpoint. All endpoints require the
storage backend to be up.
And tbh, the status endpoint is a good place to ask for status.
> verify_restservice: use the status endpoint

- .circleci/cluster/manager1_config.yaml
- .circleci/config.yml
> CY-1627 Don't upload the license in CI

- cfy_manager/components/restservice/config/authorization.conf
- Removed permissions for Deployment Metric Graph widget (CY-1788 / CY-1776)
- Removed Time Filter widget with permissions (CY-1788 / CY-1791)
> CY-1788 - Remove legacy components related to monitoring

- cfy_manager/components/status_reporter/status_reporter.py
- cfy_manager/status_reporter/status_reporter.py
- cfy_manager/utils/files.py
via file or cli commmand params
> CY-1886: adding the ability to configure status reporter

- cfy_manager/utils/files.py
- cfy_manager/utils/systemd.py
> CY-1982 Fix style/mistake issues in file rendering

- packaging/fetch_requirements
- and removing not existing rpms
> status-reporter - support for build from branch

- cfy_manager/logger.py
- cfy_manager/status_reporter/status_reporter.py
> CY-2042 status_reporter: handle --verbose

- cfy_manager/components/rabbitmq/rabbitmq.py
If the address cannot be determined then fall back to localhost
> CY-2043 brokers list: fall back to localhost if no address set

- .circleci/cluster/validate_status.sh
- .circleci/config.yml
- cfy_manager/components/mgmtworker/cluster/cluster.py
- cfy_manager/components/mgmtworker/cluster/scripts/configure_syncthing_script.py
- cfy_manager/components/mgmtworker/mgmtworker.py
- cfy_manager/components/restservice/db.py
- cfy_manager/components/restservice/restservice.py
- cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
- cfy_manager/constants.py
- cfy_manager/encryption/encryption.py
- cfy_manager/main.py
- cfy_manager/networks/networks.py
- cfy_manager/networks/scripts/update-manager-networks.py
- cfy_manager/status_reporter/status_reporter.py
- cfy_manager/utils/common.py
- cfy_manager/utils/files.py
- cfy_manager/utils/scripts.py
- cfy_manager/utils/scripts/get_encoded_user_ids.py
> CY-1905 Enable auto configuration for the manager status reporter

- cfy_manager/components/restservice/db.py
- cfy_manager/components/restservice/restservice.py
- cfy_manager/components/restservice/scripts/get_db_version.py
Disallow joining a cluster that is running a different version
of the database than the current manager
> CY-2067 Add a schema revision check when joining a cluster

- cfy_manager/components/rabbitmq/rabbitmq.py
If all nodes can be resolved, we're done! No need to continue in this function.
> CY-2080 rabbitmq: don't update /etc/hosts if all nodes can be resolved

- cfy_manager/utils/node.py
> status-reporter: moving the status reports location

- .circleci/cluster/configure_status_reporter.sh
- .circleci/cluster/validate_status.sh
- .circleci/config.yml
- Fixing cluster status check to verify the status is not failing and OK
- In cluster check, adding configuration step for all required cluster nodes for their status reporters
> CY-2126: Adding full support for cluster status in CI

- README.md
- packaging/fetch_requirements
due to that github stopped support
> github token: move to use token instead of password

- cfy_manager/components/rabbitmq/rabbitmq.py
> CY-2039 Update rabbitmq cookie in /etc/cloudify

- .circleci/config.yml
- .circleci/new_docker/config.yaml
- .circleci/new_docker/config2.yaml
- .circleci/new_docker/functions.sh
Similar to what we do on master
> CY-2151 Update CI to check cluster status

- cfy_manager/components/rabbitmq/rabbitmq.py
This way is just faster than using the API.
This saves up to 10 seconds.
.manage_users() needs to stay there because it's also used in
the runtime ("day2") commands
> CY-2839 Use definitions.json for creating rabbitmq policies

- cfy_manager/main.py
> image-starter: decode `ip a` output

- packaging/jenkins/build_docker_image.groovy
> jenkinsfile: s/edition/premium_edition/

- cfy_manager/components/composer/composer.py
- cfy_manager/components/nginx/config/composer-location.cloudify
* Changed Nginx configuration
* Updated running npm run db-migrate command
> CY-1502 - Update Composer configuration

- cfy_manager/main.py
They don't have `Wants`, they only have `After`, which is specifically
so that they can handle rabbitmq not being there.
> Don't ad-hoc rewrite unit files when not installing rabbitmq

- cfy_manager/components/prometheus/prometheus.py
... just as we do for the Manager.
> Set SELinux to permissive mode for status-reporter

- cfy_manager/main.py
This is probably a bad idea. But CY-3235 asks for it.
> CY-3235 Image starter: default password to 'admin'

- cfy_manager/components/prometheus/prometheus.py
- cfy_manager/components/rabbitmq/rabbitmq.py
- cfy_manager/utils/certificates.py
Otherwise we'll have errors when running post-install commands, e.g. cfy_manager configure.
> CY-3257 Ensure monitoring CA cert exists

- config.yaml
Removing `node_id` from the config.yaml
> CY-3290 Update config.yaml to match the new status reporter

- cfy_manager/components/sanity/blueprint/plugins/sanitycheck/setup.py
- packaging/version_info
- setup.py
This reverts commit 7468891f0ff2434c7439e1ffe306fb74ded6365a.
> Revert "Bump version"

- cfy_manager/components/restservice/config/cloudify-restservice
- cfy_manager/components/restservice/config/supervisord/cloudify-restservice.conf
- cfy_manager/components/restservice/db.py
- cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
the other part is cloudify-cosmo/cloudify-manager#2454
> RD-488 Insert permissions/roles into the db

- cfy_manager/main.py
> Reorder components: haveged first, sanity last

- cfy_manager/main.py
- cfy_manager/utils/service.py
When (re)starting, also update the service definitions
> CY-665 Reread/daemon-reload on cfy_manager start/restart

- cfy_manager/main.py
- cfy_manager/utils/common.py
Run `yum update` and a restart automatically.
Also add a `--rpm` there, which will not help _yet_, but it
will allow a next upgrade to be just `cfy_manager upgrade --rpm http://...`
with a really-single-command upgrade.
> Add `cfy_manager upgrade`

- jenkins/Jenkinsfile
- jenkins/bp/ec2-manager-install-blueprint.yaml
> Rd 932 polish jenkinsfile

- cfy_manager/components/nginx/config/rest-location.cloudify
- cfy_manager/components/restservice/config/authorization.conf
Adding `filters_get` and `filters_list`
> RD-695 Add more commands to filters

- cfy_manager/components/restservice/scripts/update_stored_manager.py
> RD-1062 update_stored_manager: fix updating broker

- cfy_manager/components/sanity/blueprint/bp.yaml
- cfy_manager/components/sanity/blueprint/plugins/sanitycheck/sanitycheck.py
> sanitycheck: cope with the new agent/group setup

- cfy_manager/components/restservice/scripts/update_stored_manager.py
> RD-1321 update-stored-manager: cope with clustered managers

- cfy_manager/config.py
Only chown in write, instead.
For load, attempt to just read it and done, and if we fail that,
only then fall back to sudo.
> RD-1372 Don't chown the config file in load

- cfy_manager/components/nginx/config/rest-location.cloudify
> Simplify rest-location.conf

- cfy_manager/components/rabbitmq/rabbitmq.py
Default erlang cookie generation is insecure (always twenty characters, always upper case A-Z), which allows for remote command execution if brute-forced.
There is no rate limiting or lockout on nodes attempting to authenticate, so the cookie needs to be made reasonably strong.
> RD-640 Never use default epmd cookies

- cfy_manager/components/restservice/db.py
> RD-2065 Fix three nodes cluster with external DB

- cfy_manager/components/execution_scheduler/execution_scheduler.py
- cfy_manager/components/nginx/nginx.py
- cfy_manager/components/restservice/restservice.py
- cfy_manager/main.py
> Rd 2123 fix rpm upgrade 530

- cfy_manager/components/restservice/config/authorization.conf
That is used for exec-groups PATCH, for setting target groups
> RD-1419 Add the execution_group_update permission

- cfy_manager/components/restservice/restservice.py
Description in https://github.com/cloudify-cosmo/cloudify-manager/pull/3044
> RD-2248 Creating system filters during upgrade

- cfy_manager/components/restservice/restservice.py
Description here https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1160
> RD-2248 Creating system filters during upgrade v6.0

- jenkins/Jenkinsfile
- packaging/source_branch
Add source_branch to export it as environment variable so that we can use it when fetch rpms
> Add source branch

- jenkins/Jenkinsfile
- jenkins/fetch_rpms
This PR is created in order to allow fetch rpms from cloudify jenkins artifacts
> RD-2436 Fetch cloudify rpms from jenkins artifacts

- packaging/fetch_requirements
Add support for generating and building resources for both premium + community from dev branch without needing to create dummy branches
> Rd 2437 add support to build from dev branch

- cfy_manager/components/postgresql_client/postgresql_client.py
In case postgres group's id (GID) does not equal 26 (which may be the
case on some systems, e.g. the ones using LDAP/Active Directory), we
should retrieve this GID while adding `postgres` user.
> RD-2619 Do not create postgres user/group for client

- cfy_manager/components/usage_collector/usage_collector.py
In case `crontab` command is not accessible during Usage Collector
installation (e.g. has disabled execute permissions), warn user and just
do not install U. C.
(a cherry-pick from `master` branch https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1191)
> RD-2625 Validate if crontab is accessible for Usage Collector

- packaging/install_rpm.spec
- setup.py
Version compliant with cloudify-manager's
> Upgrade psycopg2 to 2.9.1

- jenkins/build-pod.yaml
Move to spot NG and optimize QoS with space for burst to py36 and rpmbuild containers
> Rd-1766 optimize qos

- cfy_manager/components/restservice/config/authorization.conf
> auth.conf: declare node_update

- cfy_manager/components/composer/composer.py
- cfy_manager/components/globals.py
- cfy_manager/components/stage/stage.py
6.2.0-build version of https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1223
> WDR-77 Present bracketed IPv6 addresses to the UI

- cfy_manager/components/rabbitmq/rabbitmq.py
cherry-pick from https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1225
> WDR-79 chown rabbitmq:rabbitmq /etc/rabbitmq/erl_inetrc

- packaging/prometheus.spec
- packaging/prometheus_node_exporter.spec
- packaging/prometheus_postgres_exporter.spec
* Prometheus 2.27.1 -> 2.30.1
* node_exporter 1.1.2 -> 1.2.2
* postgres_exporter 0.9.0 -> 0.10.0
> Upgrade Prometheus and {node,postgres}_exporters

- setup.py
This fixes some logging related issues.
> RD-3265 Upgrade supervisord

- cfy_manager/components/postgresql_server/config/supervisord/etcd.conf
Otherwise it leaves etcd itself running on a stop.
> Stop etcd as group for supervisor

- packaging/fetch_requirements
Does nothing, I just want the build to not break on an invalid
argument
> fetch_reqs: add --architecture

- cfy_manager/main.py
The _all_services_installed check did not serve any purpose since we now install all components anyway.
Also added the currently-used config file to the error message.
Also enable checking that specific required services are configured for each command
> RD-3829 Make validate_components error message more useful

- cfy_manager/components/restservice/scripts/update_stored_manager.py
Not as a path.
This mirrors cloudify-cosmo/cloudify-manager#3472
> RD-3941 Pass the AMQP CA cert as data

- cfy_manager/components/postgresql_server/postgresql_server.py
Sometimes we successfully add the peer but the command fails.
This will log each failure for debug purposes, but accept that adding
succeeded, so it should sidestep this issue.
> RD-4031 Cope with etcd peerUrl exists

- cfy_manager/components/restservice/config/authorization.conf
Useful for scaling down, in dep-update.
> RD-2617 Declare the node_instance_delete permission

- cfy_manager/components/rabbitmq/rabbitmq.py
This also stops us from doing unverified checks on rabbit.
> RD-4190 Brokers list on AIO

- cfy_manager/components/sources.py
- jenkins/Jenkinsfile
- packaging/fetch_requirements
Ports https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1316
> Rd 4091 add git pkg 631

- packaging/docker/Dockerfile
> RD-4159 docker images: default to no-ssl

- cfy_manager/components/prometheus/prometheus.py
- cfy_manager/components/restservice/restservice.py
This is a patch for upgrade procedure of cloudify-restservice and Prometheus.
> RD-4352 Fix update procedure

- cfy_manager/components/mgmtworker/scripts/create-admin-token.py
We replicate the token anyway, so no need.
> RD-4497 Don't include hostname in mgmtworker token

- cfy_manager/components/postgresql_server/postgresql_server.py
This is an attempt to provide better general-use parameters for the
PostgreSQL installation.
> RD-4334 Tweak default PostgreSQL parameters

- cfy_manager/main.py
If the skip flag is set, just don't install stage. I'm keeping the
ordering (although probably inconsequential).
> RD-5465 config.yaml: honor stage.skip_installation

- cfy_manager/components/restservice/db.py
- cfy_manager/components/restservice/restservice.py
- cfy_manager/components/restservice/scripts/create_tables_and_add_defaults.py
manager_rest.configure_manager does this now
(since cloudify-cosmo/cloudify-manager#3867 and cloudify-cosmo/cloudify-manager#3869 )
> create_tables_and_add_defaults: stop inserting rabbitmqs

- cfy_manager/components/restservice/config/authorization.conf
> RD-6361 Add permissions for new widget - Secret Providers

- cfy_manager/components/postgresql_server/postgresql_server.py
- cfy_manager/components/validations.py
- cfy_manager/main.py
- cfy_manager/utils/common.py
- cfy_manager/utils/service.py
- config.yaml
Also making static all the methods that could be static in postgresql_server.py
> Rd 6429 inplace upgrade psql

- cfy_manager/components/nginx/config/manager.upstream
- cfy_manager/components/nginx/config/monitoring.upstream
> RD-6354 nginx: enable http2 support

- cfy_manager/components/restservice/scripts/update_stored_manager.py
Similar to broker, update the current db node
> update_stored_manager: update the matching db node

- cfy_manager/components/nginx/config/rest-location.cloudify
- cfy_manager/components/restservice/config/authorization.conf
- cfy_manager/main.py
- cfy_manager/utils/service.py
- jenkins/bp/ec2-manager-install-blueprint.yaml
- jenkins/build-pod.yaml
- packaging/docker-rh8/Dockerfile
- packaging/docker/Dockerfile
- packaging/files/etc/supervisord.conf
This backports the following tickets to 6.4.2:
- RD-6292
- RD-6289
- RD-6291
- RD-6290
- RD-6717
[RD-6292]: https://cloudifysource.atlassian.net/browse/RD-6292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6289]: https://cloudifysource.atlassian.net/browse/RD-6289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6291]: https://cloudifysource.atlassian.net/browse/RD-6291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6290]: https://cloudifysource.atlassian.net/browse/RD-6290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6717]: https://cloudifysource.atlassian.net/browse/RD-6717?atlOrigin=eyJpIj …
> RD-6588 6.4.2 backports

- cfy_manager/components/restservice/restservice.py
Run the script added in cloudify-cosmo/cloudify-manager#4040
> RD-6589 Upgrade: run the "compute blueprint reqs" script

- cfy_manager/components/globals.py
This setting was there, but was unused. Whoops :)
- deduplicate adding the internal listener: it was both in the ssl_enabled branch, and in the else branch, now it's separate
- add more internal listeners, based on the config
- add the external rest listener always when ssl_enabled is set, even if the cert is not defined - the cert will be created later on anyway
> RD-372 actually use additional_internal_rest_listeners

- packaging/prometheus.spec
- packaging/prometheus_blackbox_exporter.spec
- packaging/prometheus_node_exporter.spec
- packaging/prometheus_postgres_exporter.spec
> Bump prometheus & exporter versions

- packaging/install_rpm.spec
- setup.py
> bump cryptography version

- packaging/docker-rh8/Dockerfile
- packaging/docker/Dockerfile
Might as well do the update after installing all the packages, so that they're update as well, in order to always deliver the latest and greatest (of whatever is available in centos repos)
> Dockerfile: do `yum update` after all the installs
